apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-app-helm
spec:
  selector:
    matchLabels: deployment-test-app-helm
  template:
    metadata:
      labels:
        app: deployment-test-app-helm
  template:
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
